apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: biddinggo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/beyond-sw-camp/be25-4th-biddingmate-biddinggo.git
    targetRevision: main
    path: infra/k8s
    directory:
      recurse: true

  destination:
    server: 운영클러스터_SERVER값
    namespace: biddinggo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true